[package]
name = "text-embeddings-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
flume = "^0.11"
hf-hub = { version = "^0.3.0", features = ["tokio"] }
metrics = "^0.21"
text-embeddings-backend = { path = "../backends" }
thiserror = "^1.0"
tokenizers = { version = "^0.14", default-features=false, features=["onig"] }
tracing = "^0.1"
tokio = { version = "^1.25", features = ["rt", "rt-multi-thread", "parking_lot", "sync"] }
