name: Run Neuron integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run the workflow nightly to check Neuron integration is working

jobs:
  tests:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on:
      group: aws-inf2-8xlarge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build Docker image for Neuron
        run: |
          docker build . -f Dockerfile-neuron -t tei-neuron

      - name: Run integration tests
        working-directory: integration_tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DOCKER_IMAGE: tei-neuron
        run: |
          uv sync --locked --all-extras --dev
          uv run pytest --durations=0 -sv neuron/
